spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: spring_cloud_user
      password: '****************'

encrypt:
  key: ${ENCRYPT_KEY}